language: java
jdk: oraclejdk8
before_install:
  - chmod +x mvnw
cache:
  directories:
  - ~/.m2
deploy:
  provider: heroku
  app: teache-pwr-spring
  api_key: "8e1c45af-bde1-4afd-b555-3e1674ef422a"
  skip_cleanup: true
  on:
    branch: heroku